module.exports = {
  "root": "./",
  "port": 3001,
  "host": "localhost",
  "base": "",
  "id": "id",
  "dbMode": "mock",
  "reverse": false,
  "log": false,
  "noGzip": false,
  "noCors": false,
  "noCache": true,
  "readOnly": false,
  "logger": true,
  "bodyParser": true,
  "cookieParser": true,
  "db": ["product.json.json", "price.json"],
  "middlewares": "middlewares.js",
  "injectors": "injectors.json",
  "store": "store.json",
  "rewriters": "rewriters.json",
  "static": "",
  "environment": "env",
  "snapshots": "snapshots",
  "watch": true,
  "watchFiles": [],
  "ignoreFiles": [],
  "duplicates": false,
  "homePage": true,
  "openInside": true,
  "showInfoMsg": true,
  "statusBar": {
    "show": "true",
    "position": "Right",
    "priority": "0"
  }
}